project_id = "onvnvlnxmilotkxkfddu"

[functions.ai-provider-health-check]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.send-invitation]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false