// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onvnvlnxmilotkxkfddu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9udm52bG54bWlsb3RreGtmZGR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTQ1ODIsImV4cCI6MjA3Mzc5MDU4Mn0.xQZAfj_Y_2VIypEgcV7nuf0BJMMU-1CdwlxDqPByKHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});